### ISSUE TITLE
Companies location

### ISSUE THREAD

**Issue by BenGedi** [JonathanDn/vue-companies-israel#6]
It would be nice to mention the location of each company.

**Comment by JonathanDn** [comment]
I agree this might be very relevant. I would love to see what other people think. If we get a strong indication of a need for that I would love to add this to the format.

**Comment by JonathanDn** [comment]
@BenGedi  I just refactored the entire repo to @lirantal 's suggestion to make it tabular. Locations will be added in the relevant cells soon. Do you like this new direction?

**Comment by JonathanDn** [comment]
Resolved with the shift to table + location clumn
