### ISSUE TITLE
Suggestion: use tabular view for companies list to add more information

### ISSUE THREAD

**Issue by lirantal** [JonathanDn/vue-companies-israel#9]
Great work on curating this @JonathanDn ✨

I believe that turning the companies list into a table view we can add more metadata on each, such as geographic location as proposed on https://github.com/JonathanDn/vue-companies-israel/issues/6 which is an important factor when search for a job and other metrics that would be interesting.

**Comment by JonathanDn** [comment]
Thanks Liran,

I agree that it can really help with all the Metadata I just wonder if a table would make everything more cluttered and less approachable.

Maybe have both a more detailed table and a table of content with just company names, what do you think about that solution? For a quick overview and then a drill down to "the API" (metadata)

* Totally agree on 6 with Ben, wanted to see if more people are positive on that as well I see that it is important and suggest to move forward on them.

Would you like to PR the table ? I would kindly merge it if you want to contribute to this effort

**Comment by lirantal** [comment]
Some references to other similar-concept repos:
* https://github.com/yanirs/established-remote
* https://github.com/remoteintech/remote-jobs
* https://github.com/lukasz-madon/awesome-remote-job
* https://github.com/PatrickJS/remote-jobs-list

Hope this gives some ideas :-)

**Comment by lirantal** [comment]
> Maybe have both a more detailed table and a table of content with just company names

I think it will add a lot of maintenance to handle duplicates, and constant updates.

> Would you like to PR the table ? 

Go ahead and run the change if you're happy with it 😉

**Comment by JonathanDn** [comment]
Awesome stuff thank for sharing @lirantal the references.

Okay so let's start "thin" with just the table and see how it goes.

Sure I'll take care of it.

**Comment by JonathanDn** [comment]
@lirantal Just finished the refactor. Can you have a look and share if that's what you had in mind ? If so, I'll just add the locations and I think I can remove the previous list, anything else you suggest to add to the table before removing the old list?

**Comment by JonathanDn** [comment]
Just moved to the table completely :) This is resolved, thanks for a great suggestion!

**Comment by lirantal** [comment]
Looks good,I like it.
I think it will require a lot of maintenance to keep up with the recruited status. How about we add a link to the jobs?

**Comment by JonathanDn** [comment]
@lirantal I played around with this in my head. Thought from the perspective of the job-seeker it is not **real time** and not actual to just direct to the career page. Further, often its the case that career pages are not updated in time and if you got a personal contact you hear of things before they even go up. I think a lot of times positions are closed in personal cycles friend brings a friend style rather than uploading it to the career page.

You still think that when trying to balance this a career page + point of contact is good enough?

**Comment by lirantal** [comment]
Sure, let's let it flow and get some more opinions and contributions from others.

**Comment by JonathanDn** [comment]
@lirantal Would you like to open a new issue about this point so people can discover and discuss?

Currently this discussion is in a closed issue about the tabular refactor :)

**Comment by lirantal** [comment]
Ahh yes!
